# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pdx214 pdx215,$(TARGET_DEVICE)),)

endif
